### ISSUE TITLE
ROI Color Coder: Option to use log transforms

### ISSUE THREAD

**Issue by tferr** [tferr/Scripts#22]
From Kenneth R Sloan:

>The problem is the program either ignores the smaller particles or assigns all the smaller ones the same value. It doesn't differentiate size once the particle is some rather large fraction of the largest particle.
Color coding based on a function would be a way to accommodate large ranges. If the color was assigned to the log of the area for instance, that would work. One would need to have a choice.

**Comment by tferr** [comment]
I guess one could add a checkbox option to take the log of the values of the chosen parameter. @peterjlee, you have been working a lot with ROI Color Coder. What do you think?

**Comment by peterjlee** [comment]
Hi Tiago,

               Most of my size distributions are log-normal so I have 
considered adding a few lines of code to generate log-value columns in the 
results table and then using those values to color code. Weighing against me 
putting effort into that was that the frequency plot it is a little easier 
to ascribe meaning to than the color coding so the bigger plan would have 
been to code something that would also plot log-normal frequency 
distributions but as I do that in an Excel template there was no hurry. For 
now when I have one group of features that are much larger or smaller than 
the others I just set the range to give them one color (max or min): to do 
this all my ROI Color Coder variants generate overrun range labels that are 
added to the ramp (see the first example figure on the web page link below). 
This is useful when there are just a few outliers that would otherwise 
reduce the contrast variation for the majority of the features.

               I have some BAR-ROI based macros illustrated here:

               http://fs.magnet.fsu.edu/~lee/asc/ImageJUtilities/ASC_ImageJ_Utils.html

               and I did try using the fork system on GitHub (although I 
really don’t know if I am doing that right).

               My GitHub address is here: https://github.com/peterjlee

               I have co-written a book chapter that features examples of 
some of these and this should be published sometime this year. We also have 
a few papers in the works that I hope will use these routines to generate 
figures.



All the best and many thanks for BAR,

Peter



Peter J. Lee-- Assoc. Director: Applied Superconductivity Center, 2031 E. 
Paul Dirac Dr., Tallahassee, FL 32310 USA - Tel. +1 850-645-7484 - FAX-7754

**Comment by tferr** [comment]
Added a really simple log10 transformation checkbox (see ffe17bec92e3c3a5ed27b3579c020738b987b69b). If everybody is fine with it, I'd close this issue.

> I have some BAR-ROI based macros illustrated here: http://fs.magnet.fsu.edu/~lee/asc/ImageJUtilities/ASC_ImageJ_Utils.html

Really Cool stuff! Glad it has been useful.

> I have co-written a book chapter that features examples of some of these and this should be published sometime this year.

Let me know when that happens!
